server:
  port: 8015
spring:
  application:
    name: member
  cloud:
    nacos:
      discovery:
        server-addr: 8.134.216.243:8848

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto